image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - test
  - build
  - deploy

variables:
  DOTNET_CLI_HOME: "/tmp/DOTNET_CLI_HOME"

backend-tests:
  stage: test
  script:
    - dotnet restore backend
    - dotnet build backend --no-restore
    - dotnet test backend/tests --no-build --verbosity normal
  cache:
    paths:
      - backend/obj/
      - backend/bin/
    key:
      files:
        - backend/src/JobTracker.Api.csproj
  only:
    - main
    - merge_requests

frontend-tests:
  stage: test
  image: node:20
  cache:
    paths:
      - frontend/node_modules/
    key:
      files:
        - frontend/package-lock.json
  script:
    - cd frontend
    - npm ci
    - npm test -- --watchAll=false
  only:
    - main
    - merge_requests

build:
  stage: build
  script:
    # Build backend
    - cd backend
    - dotnet restore
    - dotnet build --configuration Release --no-restore
    - dotnet publish -c Release -o publish
    
    # Build frontend
    - cd ../frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - backend/publish/
      - frontend/build/
    expire_in: 1 week
  only:
    - main

deploy-backend:
  stage: deploy
  needs: ['build']
  image: mcr.microsoft.com/azure-cli
  script:
    # Install zip
    - apk add --no-cache zip

    # Deploy backend
    - cd backend/publish
    - zip -r backend.zip .
    - echo "$AZURE_WEBAPP_PUBLISH_PROFILE" > publish_profile.xml
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    - az webapp deployment source config-zip --resource-group job-app-tracker-rg --name job-app-tracker-api --src backend.zip
    
    # Update app settings if needed
    - |
      az webapp config appsettings set \
        --resource-group job-app-tracker-rg \
        --name job-app-tracker-api \
        --settings ASPNETCORE_ENVIRONMENT="Production" \
                    WEBSITE_TIME_ZONE="Pacific/Auckland"
    
    # Set CORS to allow the static web app
    - |
      az webapp cors add \
        --resource-group job-app-tracker-rg \
        --name job-app-tracker-api \
        --allowed-origins "https://job-app-tracker-static.azurestaticapps.net"
  only:
    - main
  environment:
    name: production
    url: https://job-app-tracker-api.azurewebsites.net

deploy-frontend:
  stage: deploy
  needs: ['build', 'deploy-backend']
  image: node:20
  script:
    # Install Static Web Apps CLI
    - npm install -g @azure/static-web-apps-cli
    
    # Deploy frontend using SWA CLI
    - cd frontend/build
    - swa deploy . --deployment-token "$AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN"
  only:
    - main
  dependencies:
    - build  # Explicitly pull artifacts from the build job
  environment:
    name: production
    url: https://job-app-tracker-static.azurestaticapps.net